# Generated by Django 3.0.6 on 2020-06-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0003_subcriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcriber',
            name='ref_id',
            field=models.CharField(default='asddddddddddddddasd', max_length=10, unique=False),
            preserve_default=False,
        ),
    ]
