# Generated by Django 3.0.6 on 2020-06-17 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0005_auto_20200616_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcriber',
            name='referrer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='join.Subcriber'),
        ),
    ]
