# Generated by Django 3.0.6 on 2020-06-22 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('join', '0006_subcriber_referrer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('address2', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=120)),
                ('state', models.CharField(choices=[('Tashkent', 'Tash'), ('Samarkand', 'Sam'), ('Bukhara', 'Bukh'), ('Jizzakh', 'Jiz')], max_length=120)),
                ('zip_code', models.PositiveIntegerField()),
                ('remember', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
